### PR TITLE
#38 Fix Notice Undefined index : templates in Conditions

### PR DESCRIPTION
**Pull request by vincsb**
I resolve the issue #38 which i can reproduce in four steps : 
1. Install latest Wordpress version
2. Activate a theme with no page template (example : twentyfifteen)
3. Download and activate Woosidebars
4. Go to Apparence > Widgets Areas > Add new

You can find a PHP notice in the conditions metabox : "Notice: Undefined index: templates in /.../wp-content/plugins/woosidebars/classes/class-woo-conditions.php on line 582"

It's because an empty array with 'templates' key is create before check if there is templates page in the theme. I just move this declaration, it's a minor change.

I test my change with a template page, no error.

### CODE REVIEW

**Comment by vincsb** [comment]
I follow the contribution guidelines, but I think I made a mistake to pull my request on branch release-1-4-0. I had not seen that this branch is 4 commit behind master.

It's ok for you or you want me to clean it ? :)

**Comment by vburlak** [comment]
also have the same issue. @mattyza, please merge that pull-request

**Comment by mattyza** [comment]
@vincsb @vburlak I'll clean this and cherry-pick the commit.

Thanks for submitting! :)

**Comment by vincsb** [comment]
@mattyza @vburlak Glade i could help !

**Comment by vburlak** [comment]
@mattyza thx a lot

**Comment by mattyza** [comment]
I found a slightly different solution for this, gents. I've added and tagged version 1.4.3 which contains this solution. :)

**Pull request closed without merging**
