### PR TITLE
Remove missing video from ready.txt

### PR DESCRIPTION
**Pull request by ryanr14**
The Vimeo video no longer exists and the WooSidebars video is pretty out of date, removing it for now is best. :)

### CODE REVIEW

**Comment by ryanr14** [comment]
Who wants to get this video removed for me? I'll send you a cookie!

**Comment by ryanr14** [comment]
Maaybbee @mattyza can get this in for moi? I've been waiting patiently. :)

**Comment by jobthomas** [comment]
@mattyza just had a look at the .org repo and the empty video file is still embedded there:

**Comment by mattyza** [comment]
Updated directly in the WordPress.org SVN repository. Thanks @jobthomas @ryanr14.

**Pull request merged**
